// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: classroom.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Classroom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anys       []*anypb.Any     `protobuf:"bytes,1,rep,name=anys" json:"anys,omitempty"`
	Classrooms []*Student       `protobuf:"bytes,2,rep,name=classrooms" json:"classrooms,omitempty"`
	Points     map[string]int32 `protobuf:"bytes,3,rep,name=points" json:"points,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Types that are assignable to TestOnfof:
	//
	//	*Classroom_Name
	//	*Classroom_Id
	TestOnfof isClassroom_TestOnfof `protobuf_oneof:"test_onfof"`
}

func (x *Classroom) Reset() {
	*x = Classroom{}
	mi := &file_classroom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Classroom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classroom) ProtoMessage() {}

func (x *Classroom) ProtoReflect() protoreflect.Message {
	mi := &file_classroom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classroom.ProtoReflect.Descriptor instead.
func (*Classroom) Descriptor() ([]byte, []int) {
	return file_classroom_proto_rawDescGZIP(), []int{0}
}

func (x *Classroom) GetAnys() []*anypb.Any {
	if x != nil {
		return x.Anys
	}
	return nil
}

func (x *Classroom) GetClassrooms() []*Student {
	if x != nil {
		return x.Classrooms
	}
	return nil
}

func (x *Classroom) GetPoints() map[string]int32 {
	if x != nil {
		return x.Points
	}
	return nil
}

func (m *Classroom) GetTestOnfof() isClassroom_TestOnfof {
	if m != nil {
		return m.TestOnfof
	}
	return nil
}

func (x *Classroom) GetName() string {
	if x, ok := x.GetTestOnfof().(*Classroom_Name); ok {
		return x.Name
	}
	return ""
}

func (x *Classroom) GetId() int32 {
	if x, ok := x.GetTestOnfof().(*Classroom_Id); ok {
		return x.Id
	}
	return 0
}

type isClassroom_TestOnfof interface {
	isClassroom_TestOnfof()
}

type Classroom_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,oneof"`
}

type Classroom_Id struct {
	Id int32 `protobuf:"varint,9,opt,name=id,oneof"`
}

func (*Classroom_Name) isClassroom_TestOnfof() {}

func (*Classroom_Id) isClassroom_TestOnfof() {}

var File_classroom_proto protoreflect.FileDescriptor

var file_classroom_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x02, 0x0a, 0x09,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x6e, 0x79,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61,
	0x6e, 0x79, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f,
	0x6d, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x39, 0x0a, 0x0b, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x6e,
	0x66, 0x6f, 0x66, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e,
}

var (
	file_classroom_proto_rawDescOnce sync.Once
	file_classroom_proto_rawDescData = file_classroom_proto_rawDesc
)

func file_classroom_proto_rawDescGZIP() []byte {
	file_classroom_proto_rawDescOnce.Do(func() {
		file_classroom_proto_rawDescData = protoimpl.X.CompressGZIP(file_classroom_proto_rawDescData)
	})
	return file_classroom_proto_rawDescData
}

var file_classroom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_classroom_proto_goTypes = []any{
	(*Classroom)(nil), // 0: classroom
	nil,               // 1: classroom.PointsEntry
	(*anypb.Any)(nil), // 2: google.protobuf.Any
	(*Student)(nil),   // 3: main.student
}
var file_classroom_proto_depIdxs = []int32{
	2, // 0: classroom.anys:type_name -> google.protobuf.Any
	3, // 1: classroom.classrooms:type_name -> main.student
	1, // 2: classroom.points:type_name -> classroom.PointsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_classroom_proto_init() }
func file_classroom_proto_init() {
	if File_classroom_proto != nil {
		return
	}
	file_student_proto_init()
	file_classroom_proto_msgTypes[0].OneofWrappers = []any{
		(*Classroom_Name)(nil),
		(*Classroom_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_classroom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_classroom_proto_goTypes,
		DependencyIndexes: file_classroom_proto_depIdxs,
		MessageInfos:      file_classroom_proto_msgTypes,
	}.Build()
	File_classroom_proto = out.File
	file_classroom_proto_rawDesc = nil
	file_classroom_proto_goTypes = nil
	file_classroom_proto_depIdxs = nil
}
